RDKCOM-2032 RDKBCMF-260 CcspAdvSecurity build failure for RPi and Turris Omnia
CcspAdvSecurity does not build for RPi and Turris Omnia:
| ../../../git/source/AdvSecurityDml/cosa_adv_security_internal.c:379:15: error: 'CONFIG_VENDOR_NAME' undeclared (first use in this function)
|      if(strlen(CONFIG_VENDOR_NAME) > 0)
|                ^~~~~~~~~~~~~~~~~~
It is necessary to add a #include for the ccsp_vendor.h header file.

Reason for change: RDKBCMF-260 CcspAdvSecurity build failure for RPi and Turris Omnia
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>

(cherry picked from commit 751d632b7ae932fc0bcb05416027114c18508bf5)
Change-Id: I2050b65edc943be166605e6362f87b2fb3ff6cd7